"""empty message

Revision ID: 6ba95d31f977
Revises: 
Create Date: 2026-04-07 15:29:49.543233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba95d31f977'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargo',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cargo'))
    )
    op.create_table('convenios',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_convenios'))
    )
    op.create_table('funcionario',
    sa.Column('contratacao', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('cargo_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('rg', sa.String(length=20), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('contato', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id'], name=op.f('fk_funcionario_cargo_id_cargo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_funcionario')),
    sa.UniqueConstraint('cpf', name=op.f('uq_funcionario_cpf')),
    sa.UniqueConstraint('email', name=op.f('uq_funcionario_email')),
    sa.UniqueConstraint('rg', name=op.f('uq_funcionario_rg'))
    )
    op.create_table('prontuario',
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('convenio_id', sa.Integer(), nullable=False),
    sa.Column('internacao', sa.DateTime(), nullable=False),
    sa.Column('data_saida', sa.Date(), nullable=True),
    sa.Column('motivo_saida', sa.String(), nullable=True),
    sa.Column('escolaridade', sa.String(), nullable=False),
    sa.Column('profissao', sa.String(), nullable=True),
    sa.Column('religiao', sa.String(), nullable=True),
    sa.Column('mae', sa.String(), nullable=False),
    sa.Column('estado_civil', sa.String(), nullable=False),
    sa.Column('conjuge', sa.String(), nullable=True),
    sa.Column('cartao_sus', sa.String(), nullable=True),
    sa.Column('responsavel', sa.String(), nullable=True),
    sa.Column('relacao', sa.String(), nullable=False),
    sa.Column('cpf_resp', sa.String(length=11), nullable=False),
    sa.Column('rg_resp', sa.String(length=9), nullable=False),
    sa.Column('contato_resp', sa.String(), nullable=False),
    sa.Column('contato_dois', sa.String(), nullable=True),
    sa.Column('contrib', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('rg', sa.String(length=20), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('contato', sa.String(length=100), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('rua', sa.String(length=200), nullable=True),
    sa.Column('num', sa.String(length=20), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['convenio_id'], ['convenios.id'], name=op.f('fk_prontuario_convenio_id_convenios')),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionario.id'], name=op.f('fk_prontuario_funcionario_id_funcionario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prontuario')),
    sa.UniqueConstraint('cpf', name=op.f('uq_prontuario_cpf')),
    sa.UniqueConstraint('cpf_resp', name=op.f('uq_prontuario_cpf_resp')),
    sa.UniqueConstraint('rg', name=op.f('uq_prontuario_rg')),
    sa.UniqueConstraint('rg_resp', name=op.f('uq_prontuario_rg_resp'))
    )
    op.create_table('consulta',
    sa.Column('primeiro_contato', sa.DateTime(), nullable=False),
    sa.Column('triagem', sa.DateTime(), nullable=True),
    sa.Column('modalidade', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('prontuario_id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionario.id'], name=op.f('fk_consulta_funcionario_id_funcionario')),
    sa.ForeignKeyConstraint(['prontuario_id'], ['prontuario.id'], name=op.f('fk_consulta_prontuario_id_prontuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consulta'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consulta')
    op.drop_table('prontuario')
    op.drop_table('funcionario')
    op.drop_table('convenios')
    op.drop_table('cargo')
    # ### end Alembic commands ###
