"""inicial

Revision ID: 77ccfe1d5bfc
Revises: 
Create Date: 2026-02-18 14:05:07.272788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77ccfe1d5bfc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargo',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cargo'))
    )
    op.create_table('categoria',
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categoria')),
    sa.UniqueConstraint('tipo', name=op.f('uq_categoria_tipo'))
    )
    op.create_table('fornecedores',
    sa.Column('cnpj_cpf', sa.String(length=200), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fornecedores'))
    )
    op.create_table('consulta',
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('triagem', sa.DateTime(), nullable=True),
    sa.Column('internacao', sa.DateTime(), nullable=True),
    sa.Column('hora', sa.DateTime(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], name=op.f('fk_consulta_categoria_id_categoria')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consulta'))
    )
    op.create_table('dados_bancarios',
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('banco', sa.String(length=200), nullable=False),
    sa.Column('agencia', sa.String(length=200), nullable=False),
    sa.Column('conta_corrente', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], name=op.f('fk_dados_bancarios_fornecedor_id_fornecedores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dados_bancarios'))
    )
    op.create_table('funcionario',
    sa.Column('contratacao', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('cargo_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('rg', sa.String(length=20), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id'], name=op.f('fk_funcionario_cargo_id_cargo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_funcionario')),
    sa.UniqueConstraint('cpf', name=op.f('uq_funcionario_cpf')),
    sa.UniqueConstraint('email', name=op.f('uq_funcionario_email')),
    sa.UniqueConstraint('rg', name=op.f('uq_funcionario_rg'))
    )
    op.create_table('editais',
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('num_processo', sa.Integer(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionario.id'], name=op.f('fk_editais_funcionario_id_funcionario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_editais'))
    )
    op.create_table('prontuario',
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('data_internacao', sa.DateTime(), nullable=False),
    sa.Column('data_saida', sa.Date(), nullable=True),
    sa.Column('motivo_saida', sa.String(), nullable=True),
    sa.Column('convenio', sa.String(), nullable=False),
    sa.Column('escolaridade', sa.String(), nullable=False),
    sa.Column('profissao', sa.String(), nullable=True),
    sa.Column('religiao', sa.String(), nullable=True),
    sa.Column('mae', sa.String(), nullable=False),
    sa.Column('estado_civil', sa.String(), nullable=False),
    sa.Column('conjuge', sa.String(), nullable=True),
    sa.Column('cartao_sus', sa.String(), nullable=True),
    sa.Column('responsavel', sa.String(), nullable=True),
    sa.Column('relacao', sa.String(), nullable=False),
    sa.Column('cpf_resp', sa.String(length=11), nullable=False),
    sa.Column('rg_resp', sa.String(length=9), nullable=False),
    sa.Column('contato', sa.String(), nullable=False),
    sa.Column('contato_dois', sa.String(), nullable=True),
    sa.Column('contrib', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('rg', sa.String(length=20), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('rua', sa.String(length=200), nullable=True),
    sa.Column('num', sa.String(length=20), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionario.id'], name=op.f('fk_prontuario_funcionario_id_funcionario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prontuario')),
    sa.UniqueConstraint('cpf', name=op.f('uq_prontuario_cpf')),
    sa.UniqueConstraint('cpf_resp', name=op.f('uq_prontuario_cpf_resp')),
    sa.UniqueConstraint('rg', name=op.f('uq_prontuario_rg')),
    sa.UniqueConstraint('rg_resp', name=op.f('uq_prontuario_rg_resp'))
    )
    op.create_table('rubricas',
    sa.Column('edital_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['edital_id'], ['editais.id'], name=op.f('fk_rubricas_edital_id_editais')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rubricas'))
    )
    op.create_table('despesas',
    sa.Column('rubrica_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('numero_nota', sa.String(length=200), nullable=False),
    sa.Column('data_emissao', sa.DateTime(), nullable=False),
    sa.Column('data_vencimento', sa.DateTime(), nullable=False),
    sa.Column('data_pagamento', sa.DateTime(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status_aprovacao', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], name=op.f('fk_despesas_fornecedor_id_fornecedores')),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionario.id'], name=op.f('fk_despesas_funcionario_id_funcionario')),
    sa.ForeignKeyConstraint(['rubrica_id'], ['rubricas.id'], name=op.f('fk_despesas_rubrica_id_rubricas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_despesas'))
    )
    op.create_table('documentos',
    sa.Column('despesa_id', sa.Integer(), nullable=False),
    sa.Column('url_arquivo', sa.String(length=200), nullable=False),
    sa.Column('hash_sha256', sa.String(length=200), nullable=False),
    sa.Column('extensao', sa.String(length=200), nullable=False),
    sa.Column('ocr_texto_extraido', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['despesa_id'], ['despesas.id'], name=op.f('fk_documentos_despesa_id_despesas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documentos'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentos')
    op.drop_table('despesas')
    op.drop_table('rubricas')
    op.drop_table('prontuario')
    op.drop_table('editais')
    op.drop_table('funcionario')
    op.drop_table('dados_bancarios')
    op.drop_table('consulta')
    op.drop_table('fornecedores')
    op.drop_table('categoria')
    op.drop_table('cargo')
    # ### end Alembic commands ###
