"""Adicionando colunas de endereco em funcionario

Revision ID: b01e7c04c7fb
Revises: 77ccfe1d5bfc
Create Date: 2026-02-19 15:42:39.257123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b01e7c04c7fb'
down_revision = '77ccfe1d5bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fornecedores')
    op.drop_table('documentos')
    op.drop_table('despesas')
    op.drop_table('rubricas')
    op.drop_table('editais')
    op.drop_table('dados_bancarios')
    with op.batch_alter_table('consulta', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_consulta_funcionario_id_funcionario'), 'funcionario', ['funcionario_id'], ['id'])

    with op.batch_alter_table('funcionario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cep', sa.String(length=9), nullable=True))
        batch_op.add_column(sa.Column('cidade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('rua', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('num', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bairro', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funcionario', schema=None) as batch_op:
        batch_op.drop_column('bairro')
        batch_op.drop_column('num')
        batch_op.drop_column('rua')
        batch_op.drop_column('estado')
        batch_op.drop_column('cidade')
        batch_op.drop_column('cep')

    with op.batch_alter_table('consulta', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_consulta_funcionario_id_funcionario'), type_='foreignkey')

    op.create_table('dados_bancarios',
    sa.Column('fornecedor_id', sa.INTEGER(), nullable=False),
    sa.Column('banco', sa.VARCHAR(length=200), nullable=False),
    sa.Column('agencia', sa.VARCHAR(length=200), nullable=False),
    sa.Column('conta_corrente', sa.VARCHAR(length=200), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('criado_em', sa.DATETIME(), nullable=False),
    sa.Column('atualizado_em', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], name=op.f('fk_dados_bancarios_fornecedor_id_fornecedores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dados_bancarios'))
    )
    op.create_table('editais',
    sa.Column('funcionario_id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=200), nullable=False),
    sa.Column('num_processo', sa.INTEGER(), nullable=False),
    sa.Column('valor_total', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('data_inicio', sa.DATETIME(), nullable=False),
    sa.Column('data_fim', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('criado_em', sa.DATETIME(), nullable=False),
    sa.Column('atualizado_em', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionario.id'], name='fk_editais_funcionario_id_funcionario'),
    sa.PrimaryKeyConstraint('id', name='pk_editais')
    )
    op.create_table('rubricas',
    sa.Column('edital_id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=200), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('valor', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('criado_em', sa.DATETIME(), nullable=False),
    sa.Column('atualizado_em', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['edital_id'], ['editais.id'], name='fk_rubricas_edital_id_editais'),
    sa.PrimaryKeyConstraint('id', name='pk_rubricas')
    )
    op.create_table('despesas',
    sa.Column('rubrica_id', sa.INTEGER(), nullable=False),
    sa.Column('fornecedor_id', sa.INTEGER(), nullable=False),
    sa.Column('funcionario_id', sa.INTEGER(), nullable=True),
    sa.Column('nome', sa.VARCHAR(length=200), nullable=False),
    sa.Column('numero_nota', sa.VARCHAR(length=200), nullable=False),
    sa.Column('data_emissao', sa.DATETIME(), nullable=False),
    sa.Column('data_vencimento', sa.DATETIME(), nullable=False),
    sa.Column('data_pagamento', sa.DATETIME(), nullable=False),
    sa.Column('valor', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('status_aprovacao', sa.VARCHAR(length=200), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('criado_em', sa.DATETIME(), nullable=False),
    sa.Column('atualizado_em', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], name='fk_despesas_fornecedor_id_fornecedores'),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionario.id'], name='fk_despesas_funcionario_id_funcionario'),
    sa.ForeignKeyConstraint(['rubrica_id'], ['rubricas.id'], name='fk_despesas_rubrica_id_rubricas'),
    sa.PrimaryKeyConstraint('id', name='pk_despesas')
    )
    op.create_table('documentos',
    sa.Column('despesa_id', sa.INTEGER(), nullable=False),
    sa.Column('url_arquivo', sa.VARCHAR(length=200), nullable=False),
    sa.Column('hash_sha256', sa.VARCHAR(length=200), nullable=False),
    sa.Column('extensao', sa.VARCHAR(length=200), nullable=False),
    sa.Column('ocr_texto_extraido', sa.VARCHAR(length=200), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('criado_em', sa.DATETIME(), nullable=False),
    sa.Column('atualizado_em', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['despesa_id'], ['despesas.id'], name=op.f('fk_documentos_despesa_id_despesas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documentos'))
    )
    op.create_table('fornecedores',
    sa.Column('cnpj_cpf', sa.VARCHAR(length=200), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=200), nullable=False),
    sa.Column('razao_social', sa.VARCHAR(length=200), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('criado_em', sa.DATETIME(), nullable=False),
    sa.Column('atualizado_em', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fornecedores'))
    )
    # ### end Alembic commands ###
